### ISSUE TITLE
OSError: [Errno 9] Bad file descriptor when using celery tasks on macOS

### ISSUE THREAD

**Issue by BennyThink** [pyrogram/pyrogram#841]
## Checklist
- [x] I am sure the error is coming from Pyrogram's code and not elsewhere.
- [x] I have searched in the issue tracker for similar bug reports, including closed ones.
- [x] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/master.zip` and reproduced the issue using the latest development version.

## Description

``` python
# tasks.py
#!/usr/local/bin/python3
# coding: utf-8

import logging
from pyrogram import Client
from celery import Celery

logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(filename)s [%(levelname)s]: %(message)s')

app = Celery('test', broker='redis://localhost:6379/0')


@app.task
def get_me_task():
    logging.info("celery tasks started...")
    app_id = 1234
    app_hash = "49b90"
    token = "370FXI"
    with  Client("session", app_id, app_hash,
                 bot_token=token,
                 proxy={'hostname': '127.0.0.1', 'port': 1086}
                 ) as client:
        me = client.get_me()
    print(me)
    logging.info("celery tasks ended...")


```

And in another Python console
```python
>>> from tasks import get_me_task
get_me_task.delay()
<AsyncResult: 4c55e93e-a9df-4869-b99d-7bba147e0d23>
```

## Traceback
The full traceback (if applicable).
celery -A tasks worker --loglevel=info   

```
$ celery -A tasks worker --loglevel=info                                                        

celery@BennyのMBP v5.2.2 (dawn-chorus)

macOS-10.15.7-x86_64-i386-64bit 2021-12-29 13:53:32

[config]
.> app:         test:0x105f23940
.> transport:   redis://localhost:6379/0
.> results:     disabled://
.> concurrency: 8 (prefork)
.> task events: OFF (enable -E to monitor tasks in this worker)

[queues]
.> celery           exchange=celery(direct) key=celery


[tasks]
  . tasks.get_me_task

[2021-12-29 13:53:33,309: INFO/MainProcess] Connected to redis://localhost:6379/0
[2021-12-29 13:53:33,319: INFO/MainProcess] mingle: searching for neighbors
[2021-12-29 13:53:34,337: INFO/MainProcess] mingle: all alone
[2021-12-29 13:53:34,354: INFO/MainProcess] celery@BennyのMBP ready.
[2021-12-29 13:53:49,993: INFO/MainProcess] Task tasks.get_me_task[4c55e93e-a9df-4869-b99d-7bba147e0d23] received
[2021-12-29 13:53:49,998: INFO/ForkPoolWorker-8] celery tasks started...
[2021-12-29 13:53:50,027: ERROR/ForkPoolWorker-8] Task tasks.get_me_task[4c55e93e-a9df-4869-b99d-7bba147e0d23] raised unexpected: OSError(9, 'Bad file descriptor')
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/celery/app/trace.py", line 451, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/celery/app/trace.py", line 734, in __protected_call__
    return self.run(*args, **kwargs)
  File "/Users/benny/PycharmProjects/untitled/tasks.py", line 25, in get_me_task
    with  Client("session", app_id, app_hash,
  File "/usr/local/lib/python3.9/site-packages/pyrogram/client.py", line 250, in __enter__
    return self.start()
  File "/usr/local/lib/python3.9/site-packages/pyrogram/sync.py", line 51, in async_to_sync_wrap
    return loop.run_until_complete(coroutine)
  File "/usr/local/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 629, in run_until_complete
    self.run_forever()
  File "/usr/local/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 596, in run_forever
    self._run_once()
  File "/usr/local/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 1854, in _run_once
    event_list = self._selector.select(timeout)
  File "/usr/local/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/selectors.py", line 562, in select
    kev_list = self._selector.control(None, max_ev, timeout)
OSError: [Errno 9] Bad file descriptor


```

# Environment
* Python 3.9.9 (main, Nov 21 2021, 03:22:47)
* macOS Catalina 10.15.7 
* celery@BennyのMBP v5.2.2
* master branch of pyrogram

**Tried the same code on Linux, and it's working. So it's a platform related bug? Should I reported it to celery?**

**Comment by BennyThink** [comment]
Okay closed this issue https://github.com/celery/celery/issues/6472

--pool=solo solved my issue too.
